### ISSUE TITLE
Questions on usage

### ISSUE THREAD

**Issue by TopperDEL** [anton-yashin/Plugin.Toast#1]
Thanks for you library! It is already working very well!

But I have two question:
- Is there a way to change the image/symbol shown with the Notification?
- If I click the notification - is there a way to know which one was clicked?

Thank you!

**Comment by anton-yashin** [comment]
Hi! You can change image and many other parameters by providing a implementation of IExtensionConfiguration interface. It can be like this for uwp platform: 
```c#
    sealed class IconConfiguration : IExtensionConfiguration<IUwpExtension>
    {
        public void Configure(IUwpExtension builderExtension)
        {
            builderExtension.AddAppLogoOverride(
                new Uri("https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"));
        }
    }
```
If you add this class to your DI container as implementation of IExtensionConfiguration<IUwpExtension> inside your platform project, then builder will use it automatically, or you must manually place it into builder:
```c#
builder.WhenUsing<IUwpExtension>(e => e.Use(new IconConfiguration()));
// or 
builder.WhenUsing<IUwpExtension>(e => e.Use(DependencyService.Get<IExtensionConfiguration<IUwpExtension>>));
// etc
```
At android you should use```IExtensionConfiguration<IDroidNotificationExtension>```(call a SetSmallIcon func inside override), at ios```IExtensionConfiguration<IIosNotificationExtension>```. If you need to select from multiple configurations, then use ISpecificExtensionConfiguration. It required a DI container and call of ```Use<Token>(Token token)``` function from builder.

**Comment by anton-yashin** [comment]
You also can change a platform specific setting how long it will awaits to user interaction, before notification go in the NotificationResult.TimeOut state. After Build() use ShowAsync(). You can launch and await result of more than one notification.

**Comment by anton-yashin** [comment]
If you want to detect a tap on dismissed notification. Library don't support that currently. May be i add it later.

**Comment by TopperDEL** [comment]
Thank you, @anton-yashin. To be honest I just recently switched over to "shiny", as it includes many other things as well that I needed to include in my app. So from my point, this topic can be closed.
Nevertheless, thank you for your time with this repo and for answering my questions!
